version: "3.8"
services:
    nodeserver:
        build:
            dockerfile: Dockerfile
            context: ./

    nginx:
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "80:80"
        volumes:
            - logs:/var/log/nginx
				depends_on:
					- nodeserver

volumes:
    logs:
